server:
  port: 8081

#spring data redis 配置
spring:
  web:
    resources:
      add-mappings: false # 关闭Spring Boot默认的静态资源映射
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0

logging:
  level:
    com.example.sea.auth: DEBUG

# SpringDoc 服务特定配置
springdoc:
  packages-to-scan: com.example.sea.auth
