server:
  port: 9000

spring:
  application:
    name: sea-oauth2
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: default
  security:
    oauth2:
      authorization-server:
        issuer-url: http://localhost:9000
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: lh123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
#固定字段使用配置文件
oauth2:
  client:
    id: client
    secret: secret
    redirect-uri: http://127.0.0.1:8080/login/oauth2/code/client
