server:
  port: 8081

#spring data redis 配置
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    database: 0

logging:
  level:
    com.example.sea.auth: DEBUG

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  packages-to-scan: com.example.sea.auth
  paths-to-match: /**